---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "auth-service"
  namespace: "default"
  labels:
    app: "auth-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "auth-service"
  template:
    metadata:
      labels:
        app: "auth-service"
    spec:
      containers:
      - name: "ttt-auth-service-sha256-1"
        image: "gcr.io/develop-306822/github.com/true-north-creatives/ttt-auth-service@sha256:7c879579110a5672dd29819af407173066bc3dc5b1560bb09f54c7d0c9cf2c85"
        ports:
          containerPort: 3000
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "auth-service-hpa-gi7w"
  namespace: "default"
  labels:
    app: "auth-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "auth-service"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
